.defaults:
  disallowed: &defaultDisallowed
    - status
    - kind
    - apiVersion
  properties: &defaultProperties
    enabled: metachart.interface.boolean
    metadata: metachart.api.meta.v1.ObjectMeta
  rootKey: &defaultRootKey
    disallowed: *defaultDisallowed
    properties: *defaultProperties

definitions:
  - https://raw.githubusercontent.com/iponweb/schemas/main/json-schemas/kubernetes/v1.29.3-strict/_definitions.json
  - https://raw.githubusercontent.com/iponweb/schemas/main/json-schemas/cert-manager/v1.14.5-strict/_definitions.json

rules:
  #: Common
  #:
  #: meta.v1.ObjectMeta
  - target: metachart.api.meta.v1.ObjectMeta
    source: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    allowed:
      - annotations
      - labels
      - finalizers
      - namespace
      - name
    properties:
      checksums: metachart.interface.checksums

  #: acme.cert-manager.io/v1
  - target: metachart.api.io.cert-manager.pkg.apis.acme.v1.Challenge
    source: io.cert-manager.pkg.apis.acme.v1.Challenge
    <<: *defaultRootKey

  - target: metachart.api.io.cert-manager.pkg.apis.acme.v1.Order
    source: io.cert-manager.pkg.apis.acme.v1.Order
    <<: *defaultRootKey

  #: cert-manager.io/v1
  - target: metachart.api.io.cert-manager.pkg.apis.certmanager.v1.CertificateRequest
    source: io.cert-manager.pkg.apis.certmanager.v1.CertificateRequest
    <<: *defaultRootKey

  - target: metachart.api.io.cert-manager.pkg.apis.certmanager.v1.Certificate
    source: io.cert-manager.pkg.apis.certmanager.v1.Certificate
    <<: *defaultRootKey

  - target: metachart.api.io.cert-manager.pkg.apis.certmanager.v1.ClusterIssuer
    source: io.cert-manager.pkg.apis.certmanager.v1.ClusterIssuer
    <<: *defaultRootKey

  - target: metachart.api.io.cert-manager.pkg.apis.certmanager.v1.Issuer
    source: io.cert-manager.pkg.apis.certmanager.v1.Issuer
    <<: *defaultRootKey
