.defaults:
  disallowed: &defaultDisallowed
    - status
    - kind
    - apiVersion
  properties: &defaultProperties
    enabled: metachart.interface.boolean
    metadata: metachart.api.meta.v1.ObjectMeta
  rootKey: &defaultRootKey
    disallowed: *defaultDisallowed
    properties: *defaultProperties

definitions:
  - https://raw.githubusercontent.com/iponweb/schemas/main/json-schemas/kubernetes/v1.26.15-strict/_definitions.json

rules:
  #: Common
  #:
  #: meta.v1.ObjectMeta
  - target: metachart.api.meta.v1.ObjectMeta
    source: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    allowed:
      - annotations
      - labels
      - finalizers
      - namespace
      - name
    properties:
      checksums: metachart.interface.checksums

  #: rbac.authorization.k8s.io/v1
  - target: metachart.api.io.k8s.api.rbac.v1.Role
    source: io.k8s.api.rbac.v1.Role
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.rbac.v1.RoleBinding
    source: io.k8s.api.rbac.v1.RoleBinding
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.rbac.v1.ClusterRole
    source: io.k8s.api.rbac.v1.ClusterRole
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.rbac.v1.ClusterRoleBinding
    source: io.k8s.api.rbac.v1.ClusterRoleBinding
    <<: *defaultRootKey

  #: apiregistration.k8s.io/v1
  - target: metachart.api.io.k8s.kube-aggregator.pkg.apis.apiregistration.v1.APIService
    source: io.k8s.kube-aggregator.pkg.apis.apiregistration.v1.APIService
    <<: *defaultRootKey

  #: admissionregistration.k8s.io/v1
  - target: metachart.api.io.k8s.api.admissionregistration.v1.MutatingWebhookConfiguration
    source: io.k8s.api.admissionregistration.v1.MutatingWebhookConfiguration
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.admissionregistration.v1.ValidatingWebhookConfiguration
    source: io.k8s.api.admissionregistration.v1.ValidatingWebhookConfiguration
    <<: *defaultRootKey

  #: apiextensions.k8s.io/v1
  - target: metachart.api.io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition
    source: io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition
    <<: *defaultRootKey

  #: networking.k8s.io/v1
  - target: metachart.api.io.k8s.api.networking.v1.Ingress
    source: io.k8s.api.networking.v1.Ingress
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.networking.v1.IngressClass
    source: io.k8s.api.networking.v1.IngressClass
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.networking.v1.NetworkPolicy
    source: io.k8s.api.networking.v1.NetworkPolicy
    <<: *defaultRootKey

  #: storage.k8s.io/v1
  - target: metachart.api.io.k8s.api.storage.v1.StorageClass
    source: io.k8s.api.storage.v1.StorageClass
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.storage.v1.CSIDriver
    source: io.k8s.api.storage.v1.CSIDriver
    <<: *defaultRootKey

  #: v1
  - target: metachart.api.io.k8s.api.core.v1.LimitRange
    source: io.k8s.api.core.v1.LimitRange
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.core.v1.Namespace
    source: io.k8s.api.core.v1.Namespace
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.core.v1.PodTemplate
    source: io.k8s.api.core.v1.PodTemplate
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.core.v1.ResourceQuota
    source: io.k8s.api.core.v1.ResourceQuota
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.core.v1.ServiceAccount
    source: io.k8s.api.core.v1.ServiceAccount
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.core.v1.PersistentVolume
    source: io.k8s.api.core.v1.PersistentVolume
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.core.v1.PersistentVolumeClaim
    source: io.k8s.api.core.v1.PersistentVolumeClaim
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.core.v1.ConfigMap
    source: io.k8s.api.core.v1.ConfigMap
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.core.v1.Secret
    source: io.k8s.api.core.v1.Secret
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.core.v1.Service
    source: io.k8s.api.core.v1.Service
    <<: *defaultRootKey
  #: v1 - Container
  - target: metachart.api.core.v1.Container
    source: io.k8s.api.core.v1.Container
    disallowed:
      - name
      - image
      - imagePullPolicy
    properties:
      enabled: metachart.interface.boolean
      imageRef: metachart.interface.FQDNitem
    required:
      - imageRef
  #: v1 - Pod
  - target: metachart.api.core.v1.Pod
    source: io.k8s.api.core.v1.Pod
    disallowed: *defaultDisallowed
    properties:
      <<: *defaultProperties
      spec: metachart.api.core.v1.PodSpec
  - target: metachart.api.core.v1.PodSpec
    source: io.k8s.api.core.v1.PodSpec
    properties:
      containers: metachart.api.core.v1.ContainerList
      initContainers: metachart.api.core.v1.ContainerList
      metadata: metachart.api.meta.v1.ObjectMeta

  #: apps/v1
  #:
  #: apps/v1 - Deployment
  - target: metachart.api.io.k8s.api.apps.v1.Deployment
    source: io.k8s.api.apps.v1.Deployment
    disallowed: *defaultDisallowed
    properties:
      <<: *defaultProperties
      spec: metachart.api.io.k8s.api.apps.v1.DeploymentSpec
    related:
      services: metachart.api.io.k8s.api.core.v1.Service
      poddisruptionbudgets: metachart.api.io.k8s.api.policy.v1.PodDisruptionBudget
  - target: metachart.api.io.k8s.api.apps.v1.DeploymentSpec
    source: io.k8s.api.apps.v1.DeploymentSpec
    disallowed:
      - template
      - selector
    properties:
      pod: metachart.api.core.v1.Pod
    required:
      - pod
  #: apps/v1 - Daemonset
  - target: metachart.api.io.k8s.api.apps.v1.DaemonSet
    source: io.k8s.api.apps.v1.DaemonSet
    disallowed: *defaultDisallowed
    properties:
      <<: *defaultProperties
      spec: metachart.api.io.k8s.api.apps.v1.DaemonSetSpec
    related:
      services: metachart.api.io.k8s.api.core.v1.Service
  - target: metachart.api.io.k8s.api.apps.v1.DaemonSetSpec
    source: io.k8s.api.apps.v1.DaemonSetSpec
    disallowed:
      - template
      - selector
    properties:
      pod: metachart.api.core.v1.Pod
    required:
      - pod
  #: apps/v1 - StatefulSet
  - target: metachart.api.io.k8s.api.apps.v1.StatefulSet
    source: io.k8s.api.apps.v1.StatefulSet
    disallowed: *defaultDisallowed
    properties:
      <<: *defaultProperties
      spec: metachart.api.io.k8s.api.apps.v1.StatefulSetSpec
    related:
      services: metachart.api.io.k8s.api.core.v1.Service
      poddisruptionbudgets: metachart.api.io.k8s.api.policy.v1.PodDisruptionBudget
  - target: metachart.api.io.k8s.api.apps.v1.StatefulSetSpec
    source: io.k8s.api.apps.v1.StatefulSetSpec
    disallowed:
      - template
      - selector
    properties:
      pod: metachart.api.core.v1.Pod
      volumeClaimTemplates: metachart.api.internal.volumeClaimTemplates
    required:
      - pod

  #: autoscaling/v2
  - target: metachart.api.io.k8s.api.autoscaling.v2.HorizontalPodAutoscaler
    source: io.k8s.api.autoscaling.v2.HorizontalPodAutoscaler
    <<: *defaultRootKey

  #: batch/v1
  #:
  #: batch/v1 - CronJob
  - target: metachart.api.io.k8s.api.batch.v1.CronJob
    source: io.k8s.api.batch.v1.CronJob
    disallowed: *defaultDisallowed
    properties:
      <<: *defaultProperties
      spec: metachart.api.io.k8s.api.batch.v1.CronJobSpec
  - target: metachart.api.io.k8s.api.batch.v1.CronJobSpec
    source: io.k8s.api.batch.v1.CronJobSpec
    disallowed:
      - jobTemplate
      - selector
    properties:
      job: metachart.api.io.k8s.api.batch.v1.Job
    required:
      - job
  #: batch/v1 - Job
  - target: metachart.api.io.k8s.api.batch.v1.Job
    source: io.k8s.api.batch.v1.Job
    disallowed: *defaultDisallowed
    properties:
      <<: *defaultProperties
      spec: metachart.api.io.k8s.api.batch.v1.JobSpec
  - target: metachart.api.io.k8s.api.batch.v1.JobSpec
    source: io.k8s.api.batch.v1.JobSpec
    disallowed:
      - template
    properties:
      pod: metachart.api.core.v1.Pod
    required:
      - pod

  #: certificates.k8s.io/v1
  - target: metachart.api.io.k8s.api.certificates.v1.CertificateSigningRequest
    source: io.k8s.api.certificates.v1.CertificateSigningRequest
    <<: *defaultRootKey

  #: policy/v1
  - target: metachart.api.io.k8s.api.policy.v1.PodDisruptionBudget
    source: io.k8s.api.policy.v1.PodDisruptionBudget
    <<: *defaultRootKey

  #: scheduling.k8s.io/v1
  - target: metachart.api.io.k8s.api.scheduling.v1.PriorityClass
    source: io.k8s.api.scheduling.v1.PriorityClass
    <<: *defaultRootKey

  #: flowcontrol.apiserver.k8s.io/v1beta3
  - target: metachart.api.io.k8s.api.flowcontrol.v1beta3.FlowSchema
    source: io.k8s.api.flowcontrol.v1beta3.FlowSchema
    <<: *defaultRootKey
  - target: metachart.api.io.k8s.api.flowcontrol.v1beta3.PriorityLevelConfiguration
    source: io.k8s.api.flowcontrol.v1beta3.PriorityLevelConfiguration
    <<: *defaultRootKey
