.defaults:
  disallowed: &defaultDisallowed
    - status
    - kind
    - apiVersion
  properties: &defaultProperties
    enabled: metachart.interface.boolean
    metadata: metachart.api.meta.v1.ObjectMeta
  rootKey: &defaultRootKey
    disallowed: *defaultDisallowed
    properties: *defaultProperties

definitions:
  - https://raw.githubusercontent.com/iponweb/schemas/main/json-schemas/kubernetes/v1.25.2-strict/_definitions.json
  - https://raw.githubusercontent.com/iponweb/schemas/main/json-schemas/karpenter/v0.19.1-strict/_definitions.json

rules:
  #: Common
  #:
  #: meta.v1.ObjectMeta
  - target: metachart.api.meta.v1.ObjectMeta
    source: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
    allowed:
      - annotations
      - labels
      - finalizers
      - namespace
      - name
    properties:
      checksums: metachart.interface.checksums

  #: karpenter.k8s.aws/v1alpha1
  - target: metachart.api.sh.karpenter.pkg.apis.v1alpha1.AWSNodeTemplate
    source: sh.karpenter.pkg.apis.v1alpha1.AWSNodeTemplate
    <<: *defaultRootKey

  #: karpenter.sh/v1alpha5
  - target: metachart.api.sh.karpenter.pkg.apis.v1alpha5.Provisioner
    source: sh.karpenter.pkg.apis.v1alpha5.Provisioner
    <<: *defaultRootKey
