#:
#: Demo Prometheus resource. Not a working example.
#:

prometheuses:
  main:
    spec:
      enableAdminAPI: false
      evaluationInterval: 30s
      externalUrl: http://prometheus.example.com/
      image: quay.io/prometheus/prometheus:v2.35.0
      listenLocal: false
      logFormat: logfmt
      logLevel: info
      paused: false
      portName: http-web
      replicas: 1
      retention: 30d
      routePrefix: /
      scrapeInterval: 30s
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      shards: 1
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
            storageClassName: prometheus
      version: v2.35.0
